sudo: required
dist: trusty
language: node_js
node_js:
  - '8.0.0'
install:
  - npm install -g truffle@beta
  - npm install -g ethereumjs-testrpc
  - npm install
script:
  - npm test
before_script:
  - testrpc > /dev/null &
  - sleep 5
after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls

  